# Generated by Django 3.1 on 2020-08-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('navers', '0001_initial'),
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=80)),
                ('inicio_projeto', models.DateField()),
                ('fim_projeto', models.DateField()),
                ('descricao', models.TextField(max_length=1000)),
                ('id_cargos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargos.cargo')),
                ('id_emrpesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('id_nevedex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='navers.navedex')),
            ],
        ),
    ]
