# Generated by Django 3.1 on 2020-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navedex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fone', models.CharField(blank=True, max_length=15, null=True)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
