# Generated by Django 3.1 on 2020-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navers', '0002_navedex_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navedex',
            name='data_cadastro',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
